# SPDX-FileCopyrightText: 2025 The Open Source Project Template Authors
#
# SPDX-License-Identifier: CC0-1.0
name: Lint Public Code MetaData
on: [workflow_call] # yamllint disable-line rule:truthy
permissions:
  contents: read
jobs:
  publiccode_validation:
    name: publiccode validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: italia/publiccode-parser-action@360aac457ebcdee729754996a1816df662879cb0 # v1.3.3
        with:
          publiccode: "publiccode.yml"

