# SPDX-FileCopyrightText: 2025 The Open Source Project Template Authors
#
# SPDX-License-Identifier: CC0-1.0
name: Lint Public Code MetaData
on: [workflow_call] # yamllint disable-line rule:truthy
permissions:
  contents: read
jobs:
  publiccode_validation:
    name: publiccode validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: italia/publiccode-parser-action@be6d3e9cb10c1cf556ce02831e2a6bc9cee6c2ee # v1.3.4
        with:
          publiccode: "publiccode.yml"

